apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: upgrade-plan
  namespace: system-upgrade 
spec:
  concurrency: 1 
  cordon: true 
  nodeSelector:
    matchExpressions:
    - key: k3s-upgrade 
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade 
  upgrade:
    image: rancher/k3s-upgrade 
  version: v1.22.15+k3s1 
